[build]
  publish = "dist"
  command = "vite build"

# Proxy /studio to the Sanity-hosted studio
[[redirects]]
  from = "/studio/*"
  to = "https://ambalan.sanity.studio/:splat"
  status = 200
  force = true

# Main app routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
